import {
  HeaderKeys,
  RequiredColumnMainProps,
  CreateProjectValidationInitialProps,
} from "./type";

export const DatabasesDictionaries = {
  laboratory: "laboratory",
  emr: "emr",
};

export const dictionaryConverter: HeaderKeys = {
  laboratory: {
    test_request: "test",
    age: "age",
    firstname: "firstname",
    lastname: "lastname",
    gender: "gender",
    patient_contact: "patient_contact",
    provider_name: "provider_name",
    diagnosis: "diagnosis",
    region: "region",
    provider_contact: "provider_contact",
  },
  emr: {
    age: "age",
    firstname: "patient_first_name",
    lastname: "patient_last_name",
    gender: "sex",
    provider_name: "provider_name",
    diagnosis: "diagnosis",
    region: "state",
    procedure_desc: "procedure_description",
    provider_contact: "provider_contact",
    facility_name: "name_of_facility",
    facility_location: "facility_region",
  },
  claims: {
    diagnosis: "diagnosis_description",
    firstname: "firstname",
    lastname: "lastname",
    patient_contact: "patient_contact",
    region: "state",
    gender: "gender",
    provider_name: "provider_name",
    provider_contact: "provider_contact",
    procedure_desc: "item",
    age: "dob",
    facility_location: "city",
    facility_name: "facility_name",
  },
};

export const Columns: RequiredColumnMainProps = [
  {
    id: "1",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Diagnosis",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "2",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "DiagnosisCode",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "3",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Gender",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "4",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Age",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "5",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "ProcedureDescription",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "6",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Date",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "7",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Cost",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "8",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "FacilityType",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "9",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "FacilityName",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "10",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "TestRequest",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "11",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "TestResult",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "12",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "DosageOfDrug",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "13",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "DosageFrequency",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "14",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Region",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "15",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Product",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "16",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Inpatient",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "17",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Outpatient",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "18",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "FacilityLocation",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "19",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "PatientID",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "20",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "SpecimenType",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "21",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "FirstName",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "22",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "MiddleName",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "23",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "LastName",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "24",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "DateOfBirth",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "25",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "SateOfOrigin",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "26",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "ProviderID",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "27",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "ProviderName",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "28",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "Specialty",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "29",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "PatientContact",
    dictionaryKeys: dictionaryConverter,
  },
  {
    id: "30",
    isSelected: false,
    entries: "",
    exclude: "",
    column: "ProviderContact",
    dictionaryKeys: dictionaryConverter,
  },
];

export const createProjectValidationInitial: CreateProjectValidationInitialProps =
  {
    projectName: "",
    startDate: "",
    endDate: "",
    sampleSize: 0,
  };
